Traceback (most recent call last):
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Heviaa\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Memisahkan fitur dan target
X = df[['Open', 'High', 'Low', 'Close', 'Volume']]  # Fitur
y = df['Close Target']  # Target

# Membagi data menjadi training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[11], line 2[0m
[0;32m      1[0m [38;5;66;03m# Memisahkan fitur dan target[39;00m
[1;32m----> 2[0m X [38;5;241m=[39m [43mdf[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mOpen[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mHigh[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mLow[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mClose[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mVolume[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m  [38;5;66;03m# Fitur[39;00m
[0;32m      3[0m y [38;5;241m=[39m df[[38;5;124m'[39m[38;5;124mClose Target[39m[38;5;124m'[39m]  [38;5;66;03m# Target[39;00m
[0;32m      5[0m [38;5;66;03m# Membagi data menjadi training dan testing[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py:3899[0m, in [0;36mDataFrame.__getitem__[1;34m(self, key)[0m
[0;32m   3897[0m     [38;5;28;01mif[39;00m is_iterator(key):
[0;32m   3898[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[1;32m-> 3899[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[0;32m   3901[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[0;32m   3902[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py:6115[0m, in [0;36mIndex._get_indexer_strict[1;34m(self, key, axis_name)[0m
[0;32m   6112[0m [38;5;28;01melse[39;00m:
[0;32m   6113[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[1;32m-> 6115[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[0;32m   6117[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[0;32m   6118[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[0;32m   6119[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py:6179[0m, in [0;36mIndex._raise_if_missing[1;34m(self, key, indexer, axis_name)[0m
[0;32m   6176[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[0;32m   6178[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m-> 6179[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[1;31mKeyError[0m: "['Volume'] not in index"

